---
title: "Estimation Approach to Statistical Inference"
author: "Craig A. Wendorf"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    collapse: true
    theme: cerulean
    highlight: tango
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{Exploratory Analyses Repeated Measures Data Applications}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,include=FALSE}
if(!require(EASI)) {
if(!require(devtools)) install.packages('devtools')
devtools::install_github("cwendorf/EASI")}
library(EASI)
```

## Exploratory Analyses Repeated Measures Data Applications

### Data Management

#### Data Entry

```{r}
Outcome1 <- rnorm(100,10,2)
Outcome2 <- c(rnorm(50,7,1),rnorm(50,13,1))
Outcome3 <- c(rnorm(25,7,1),rnorm(75,11,1))
RepeatedData <- data.frame(Outcome1,Outcome2,Outcome3)
```

#### Descriptive Statistics

```{r}
describePercentiles(RepeatedData)
```

### Standard Plots

#### Boxplots

```{r,Repeated-Boxes}
plotBoxes(RepeatedData)
```

#### Density Plots

```{r,Repeated-Density}
plotDensity(RepeatedData)
```

#### Data Plots

```{r,Repeated-Data}
plotData(RepeatedData)
```

### Advanced Plots

#### Violin Plots

```{r,Repeated-ViolinsA}
plotBoxes(RepeatedData,values=FALSE,main="Violin Plots")
plotDensity(RepeatedData,add=TRUE,offset=0,type="full")
```

```{r,Repeated-ViolinsB}
plotViolins(RepeatedData,col=c("darkblue","darkred","darkgoldenrod"))
```

#### Bean Plots

```{r,Repeated-BeansA}
plotDensity(RepeatedData,type="full",offset=0,main="Bean Plots")
plotData(RepeatedData,add=TRUE,offset=0,pch=95)
```

```{r,Repeated-BeansB}
plotBeans(RepeatedData,col=c("darkblue","darkred","darkgoldenrod"))
```

#### Raincloud Plots

```{r,Repeated-RaincloudsA}
plotBoxes(RepeatedData,values=FALSE,main="Raincloud Plots")
plotDensity(RepeatedData,add=TRUE,offset=.1)
plotData(RepeatedData,add=TRUE,method="jitter",offset=-.15)
```

```{r,Repeated-RaincloudsB}
plotRainclouds(RepeatedData,col=c("darkblue","darkred","darkgoldenrod"))
```

#### Combination Plots

```{r,Repeated-CombinationsA}
plotBoxes(RepeatedData,main="Combination Plots")
plotDensity(RepeatedData,add=TRUE)
plotFrequencies(RepeatedData,add=TRUE)
plotData(RepeatedData,add=TRUE)
```

```{r,Repeated-CombinationsB}
plotCombination(RepeatedData,col=c("darkblue","darkred","darkgoldenrod"))
```
