---
title: "Estimation Approach to Statistical Inference"
author: "Craig A. Wendorf"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    collapse: true
    theme: cerulean
    highlight: tango
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{Exploratory Analyses OneWay Data Applications}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,include=FALSE}
if(!require(EASI)) {
if(!require(devtools)) install.packages('devtools')
devtools::install_github("cwendorf/EASI")}
library(EASI)
```

## Exploratory Analyses OneWay Data Applications

### Data Management

#### Data Entry

```{r}
Factor <- c(rep(1,100),rep(2,100),rep(3,100))
Factor <- factor(Factor,levels=c(1,2,3),labels=c("Group1","Group2","Group3"))
Group1 <- rnorm(100,10,2)
Group2 <- c(rnorm(50,7,1),rnorm(50,13,1))
Group3 <- c(rnorm(25,7,1),rnorm(75,11,1))
Outcome <- c(Group1,Group2,Group3)
```

#### Descriptive Statistics

```{r}
describePercentiles(Outcome~Factor)
```

### Standard Plots

#### Boxplots

```{r,OneWay-Boxes}
plotBoxes(Outcome~Factor)
```

#### Density Plots

```{r,OneWay-Density}
plotDensity(Outcome~Factor)
```

####  Data Plots

```{r,OneWay-Data}
plotData(Outcome~Factor)
```

### Advanced Plots

#### Violin Plots

```{r,OneWay-ViolinsA}
plotBoxes(Outcome~Factor,values=FALSE,main="Violin Plots")
plotDensity(Outcome~Factor,add=TRUE,offset=0,type="full")
```

```{r,OneWay-ViolinsB}
plotViolins(Outcome~Factor,col=c("darkblue","darkred","darkgoldenrod"))
```

#### Bean Plots

```{r,OneWay-BeansA}
plotDensity(Outcome~Factor,type="full",offset=0,main="Bean Plots")
plotData(Outcome~Factor,add=TRUE,offset=0,pch=95)
```

```{r,OneWay-BeansB}
plotBeans(Outcome~Factor,col=c("darkblue","darkred","darkgoldenrod"))
```

#### Raincloud Plots

```{r,OneWay-RaincloudsA}
plotBoxes(Outcome~Factor,values=FALSE,main="Raincloud Plots")
plotDensity(Outcome~Factor,add=TRUE,offset=.1)
plotData(Outcome~Factor,add=TRUE,method="jitter",offset=-.15)
```

```{r,OneWay-RaincloudsB}
plotRainclouds(Outcome~Factor,col=c("darkblue","darkred","darkgoldenrod"))
```

#### Combination Plots

```{r,OneWay-CombinationsA}
plotBoxes(Outcome~Factor,main="Combination Plots")
plotDensity(Outcome~Factor,add=TRUE)
plotFrequencies(Outcome~Factor,add=TRUE)
plotData(Outcome~Factor,add=TRUE)
```

```{r,OneWay-CombinationsB}
plotCombination(Outcome~Factor,col=c("darkblue","darkred","darkgoldenrod"))
```
