---
title: "Estimation Approach to Statistical Inference"
author: "Craig A. Wendorf"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    collapse: true
    theme: cerulean
    highlight: tango
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{Frequencies Repeated Measures Data Application}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,include=FALSE}
if(!require(EASI)) {
if(!require(devtools)) install.packages('devtools')
devtools::install_github("cwendorf/EASI")}
library(EASI)
```

## Frequencies Repeated Measures Data Application

### Data Management

Simulate some data.
```{r}
Outcome1 <- round(rnorm(50,mean=7,sd=2),0)
Outcome2 <- round(rnorm(50,mean=11,sd=4),0)
Outcome3 <- round(rnorm(50,mean=12,sd=4),0)
RepeatedData <- data.frame(Outcome1,Outcome2,Outcome3)
```

### Frequency Distributions

Describe and plot the frequency distributions.
```{r,Frequencies-Repeated-FrequenciesA}
(RepeatedData) |> describeFrequencies()
(RepeatedData) |> plotFrequencies()
```

Enhance the frequency distribution plot by adding color.
```{r,Frequencies-Repeated-FrequenciesB}
(RepeatedData) |> plotFrequencies(offset=0,col=c("darkblue","darkred","darkgoldenrod"))
```

### Percentiles and Boxes

Describe the percretiles and plot the boxes.
```{r,Frequencies-Repeated-BoxesA}
(RepeatedData) |> describePercentiles()
(RepeatedData) |> describeBoxes()
(RepeatedData) |> plotBoxes()
```

Enhance the frequency distribution plot by adding color.
```{r,Frequencies-Repeated-BoxesB}
(RepeatedData) |> plotBoxes(values=FALSE,offset=0,scale=3,col=c("darkblue","darkred","darkgoldenrod"))
```
