---
subtitle: "Frequencies OneWay Data Application"
output:
  github_document:
    preserve_yaml: FALSE
vignette: >
  %\VignetteIndexEntry{Frequencies OneWay Data Application}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
knitr::opts_chunk$set(fig.width = 7, fig.height = 5, fig.path = "figures/", echo = TRUE, warning = FALSE, message = FALSE)
devtools::source_gist("8e6e5dc401e3fc1042ef7a030f9d19c7", filename = "revised_toc.R")
```

```{r,include=FALSE}
if (!require(EASI)) {
  if (!require(remotes)) install.packages("remotes")
  remotes::install_github("cwendorf/EASI")
}
library(EASI)
```

## Frequencies OneWay Data Application

This page provides basic data plots and frequency distributions using one-way (between-subjects) data.

```{r toc, echo=FALSE}
thisfile <- knitr::current_input()
revised_toc(thisfile, base_level = 3, toc_depth = 4)
```

---

### Data Management

Simulate some data.
```{r}
Factor <- c(rep(1, 50), rep(2, 50), rep(3, 50))
Factor <- factor(Factor, levels = c(1, 2, 3), labels = c("Level1", "Level2", "Level3"))
Level1 <- round(rnorm(50, mean = 7, sd = 2), 0)
Level2 <- round(rnorm(50, mean = 11, sd = 4), 0)
Level3 <- round(rnorm(50, mean = 12, sd = 4), 0)
Outcome <- c(Level1, Level2, Level3)
```

### Data Plots

Plot the data and enhance with color.
```{r,Frequencies-OneWay-Data}
(Outcome ~ Factor) |> plotData(offset = 0, method = "jitter", col = c("darkred", "darkblue", "darkgoldenrod"))
```

### Frequency Distributions

Describe the frequency distributions.
```{r}
(Outcome ~ Factor) |> describeFrequencies()
```

Plot the frequency distributions and enhance with color.
```{r,Frequencies-OneWay-Frequencies}
(Outcome ~ Factor) |> plotFrequencies(offset = 0, col = c("darkred", "darkblue", "darkgoldenrod"))
```
