---
title: "Estimation Approach to Statistical Inference"
author: "Craig A. Wendorf"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    collapse: true
    theme: cerulean
    highlight: tango
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{Relational OneWay Data Application}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,include=FALSE}
if(!require(EASI)) {
if(!require(devtools)) install.packages('devtools')
devtools::install_github("cwendorf/EASI")}
library(EASI)
```

## Relational OneWay Data Application

### Data Management

Enter the data.
```{r}
Factor <- c(rep(1,10),rep(2,10),rep(3,10),rep(4,10),rep(5,10))
Outcome <- c(61,64,72,64,64,70,73,65,65,72,69,74,79,69,64,64,69,69,74,79,70,75,80,80,70,65,70,75,70,70,70,80,85,75,70,65,75,75,85,80,65,55,70,65,65,70,70,60,65,70)
Factor <- factor(Factor,levels=c(1,2,3,4,5),labels=c("Level1","Level2","Level3","Level4","Level5"))
```

### Omnibus Analyses

Provide descriptive statistics and an ANOVA source table.
```{r}
(Outcome~Factor) |> describeMeans()
(Outcome~Factor) |> describeMeansOmnibus()
(Outcome~Factor) |> testMeansOmnibus()
```

### Analyses of Relational Intervals

Provide and plot estimates of the arelational and relational intervals.
```{r,Relational-OneWay-RelationalA}
(Outcome~Factor) |> estimateMeansRelational()
(Outcome~Factor) |> plotMeansRelational()
```

Enhance the plot by adding color.
```{r,Relational-OneWay-RelationalB}
colorTheme=c('#882e72','#1965b0','#4eb265','#ee8026','#a5170e')
(Outcome~Factor) |> plotMeansRelational(col=colorTheme)
```
