---
title: "Estimation Approach to Statistical Inference"
author: "Craig A. Wendorf"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    collapse: true
    theme: cerulean
    highlight: tango
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{Relational Intervals OneWay Data Applications}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,include=FALSE}
if(!require(EASI)) {
if(!require(devtools)) install.packages('devtools')
devtools::install_github("cwendorf/EASI")}
library(EASI)
```

## Relational Intervals OneWay Data Applications

### Data Management

```{r}
Group <- c(rep(1,10),rep(2,10),rep(3,10),rep(4,10),rep(5,10))
Outcome <- c(61,64,72,64,64,70,73,65,65,72,69,74,79,69,64,64,69,69,74,79,70,75,80,80,70,65,70,75,70,70,70,80,85,75,70,65,75,75,85,80,65,55,70,65,65,70,70,60,65,70)
Group <- factor(Group,levels=c(1,2,3,4,5),labels=c("Group1","Group2","Group3","Group4","Group5"))
```

### Analyses of Relational Intervals

Provide descriptive statistics and ANOVA source table
```{r}
(Outcome~Group) |> describeMeans()
(Outcome~Group) |> describeMeansOmnibus()
(Outcome~Group) |> testMeansOmnibus()
```

Provide and plot estimates of the arelational and relational intervals
```{r,OneWay-Relational}
(Outcome~Group) |> estimateMeansRelational()
(Outcome~Group) |> plotMeansRelational()
```
