# Estimation Approach to Statistical Inference
## Source All Available EASI Functions

source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/cipX.R")
source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/formatX.R")
source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/xBoxes.R")
source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/xCorrelations.R")
source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/xData.R")
source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/xMeanComparison.R")
source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/xMeanContrast.R")
source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/xMeanDifference.R")
source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/xMeansOmnibus.R")
source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/xMeanSubsets.R")
source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/xMeans.R")
source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/xPairwise.R")
source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/xRelational.R")
source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/StandardizedMeanContrast.R")
source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/StandardizedMeanDifference.R")
source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/StandardizedMeans.R")
source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/StandardizedMeansPairwise.R")
source("http://raw.githubusercontent.com/cwendorf/EASI/master/R/xViolins.R")
