---
title: "Estimation Approach to Statistical Inference"
author: "Craig A. Wendorf"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{Repeated Measures (Within-Subjects) Example with Donohue Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,include=FALSE}
library(EASI)
```

## Repeated Measures (Within-Subjects) Example with Donohue Data

### Enter Data

```{r}
Pretest <- c(7,11,11,13,15,17,18,18,19,19,19,19,21,22,25,25,25,26,27,29)
Posttest <- c(16,20,25,22,28,12,16,26,21,22,26,30,23,27,23,27,28,24,28,28)
Followup <- c(16,18,23,21,27,21,18,21,24,21,27,28,18,27,23,28,31,18,31,27)
DonohueData <- data.frame(Pretest,Posttest,Followup)
```
### Analyses of the Different Variables

```{r}
estimateMeans(Pretest,Posttest,Followup)
```

```{r,Donohue-Means}
plotMeans(Pretest,Posttest,Followup,ylab="Critical Thinking")
```
 
### Analysis of a Variable Difference

```{r}
estimateDifference(Posttest,Followup)
```

```{r,Donohue-Difference}
plotDifference(Posttest,Followup,ylab="Critical Thinking")
```

```{r}
standardizeDifference(Posttest,Followup)
```

### Analysis of a Variable Contrast

```{r}
PrevsPostFollow <- c(-1,.5,.5)
estimateContrast(Pretest,Posttest,Followup,contrast=PrevsPostFollow)
```

```{r,Donohue-Contrast}
plotContrast(Pretest,Posttest,Followup,contrast=PrevsPostFollow,labels=c("Pretest","Post&Follow"),ylab="Critical Thinking")
```

```{r}
testContrast(Pretest,Posttest,Followup,contrast=PrevsPostFollow)
```

```{r}
standardizeContrast(Pretest,Posttest,Followup,contrast=PrevsPostFollow)
```
