---
title: "Estimation Approach to Statistical Inference"
author: "Craig A. Wendorf"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{Repeated Measures (Within-Subjects) Example with Donohue Summary Statistics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,include=FALSE}
library(EASI)
```

## Repeated Measures (Within-Subjects) Example with Donohue Summary Statistics

### Enter Summary Statistics

```{r}
Pretest <- c(N=20,M=19.300,SD=5.904)
Posttest <- c(N=20,M=23.600,SD=4.762)
Followup <- c(N=20,M=23.400,SD=4.616)
DonohueSummary <- rbind(Pretest,Posttest,Followup)
class(DonohueSummary) <- "wss"
```

```{r}
DonohueCorr <- declareCorrMatrix("Pretest","Posttest","Followup")
DonohueCorr["Pretest","Posttest"] <- .493
DonohueCorr["Pretest","Followup"] <- .536
DonohueCorr["Posttest","Followup"] <- .743
DonohueCorr <- fillCorrMatrix(DonohueCorr)
```

### Analyses of the Different Variables

```{r}
estimateMeans(DonohueSummary)
```

```{r,Donohue-Means}
plotMeans(DonohueSummary,ylab="Critical Thinking")
```
 
### Analysis of a Variable Difference

```{r}
PostvsFollowup <- DonohueSummary[c(2,3),]
class(PostvsFollowup) <- "wss"
estimateDifference(PostvsFollowup,DonohueCorr)
```

```{r,Donohue-Difference}
plotDifference(PostvsFollowup,DonohueCorr,ylab="Critical Thinking")
```

```{r}
standardizeDifference(PostvsFollowup,DonohueCorr)
```

### Analysis of a Variable Contrast

```{r}
PrevsPostFollow <- c(-1,.5,.5)
estimateContrast(DonohueSummary,DonohueCorr,contrast=PrevsPostFollow)
```

```{r,Donohue-Contrast}
plotContrast(DonohueSummary,DonohueCorr,contrast=PrevsPostFollow,labels=c("Pretest","Post&Follow"),ylab="Critical Thinking")
```

```{r}
testContrast(DonohueSummary,DonohueCorr,contrast=PrevsPostFollow)
```

```{r}
standardizeContrast(DonohueSummary,DonohueCorr,contrast=PrevsPostFollow)
```
