---
title: "Estimation Approach to Statistical Inference"
author: "Craig A. Wendorf"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{Indendent Groups Example with PenLaptop Summary Statistics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,include=FALSE}
library(EASI)
```

## Indendent Groups Example with PenLaptop Summary Statistics

### PenLaptop1 Example

```{r}
Pen <- c(N=34,M=8.812,SD=4.749)
Laptop <- c(N=31,M=14.519,SD=7.286)
PenLaptop1Summary <- rbind(Pen,Laptop)
class(PenLaptop1Summary) <- "bss"
```

```{r,PenLaptop1-Difference}
plotDifference(PenLaptop1Summary,ylab="Transcription")
```

```{r}
standardizeDifference(PenLaptop1Summary)
```

### PenLaptop2 Example

```{r}
Pen <- c(N=48,M=6.881,SD=4.219)
Laptop <- c(N=103,M=12.088,SD=5.525)
PenLaptop2Summary <- rbind(Pen,Laptop)
class(PenLaptop2Summary) <- "bss"
```

```{r,PenLaptop2-Difference}
plotDifference(PenLaptop2Summary,ylab="Transcription")
```

```{r}
standardizeDifference(PenLaptop2Summary)
```

### PenLaptop3 Example

```{r}
Pen <- c(N=54,M=4.178,SD=2.549)
Laptop <- c(N=55,M=11.622,SD=5.681)
PenLaptop3Summary <- rbind(Pen,Laptop)
class(PenLaptop3Summary) <- "bss"
```

```{r,PenLaptop3-Difference}
plotDifference(PenLaptop3Summary,ylab="Transcription")
```

```{r}
standardizeDifference(PenLaptop3Summary)
```
