---
title: "Estimation Approach to Statistical Inference"
author: "Craig A. Wendorf"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{OneWay (Between-Subjects) Example with Rattan Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,include=FALSE}
library(EASI)
```

## OneWay (Between-Subjects) Example with Rattan Data

### Enter Data

```{r}
Feedback <- c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3)
Motivation <- c(5.5,5,5.5,6,1,2.5,4.5,1,3.5,1.5,5.5,6,1.5,1,3.5,2.5,3,1,2,6,4.5,4.5,6,7,3,7,3.5,5,4.5,5.5,6.5,6,6,7,5.5,6,2.5,4.5,3.5,6,5,6,3.5,4,3,5.5,3,6,3,5,6,6.5,3.5,2)
Feedback <- factor(Feedback,levels=c(1,2,3),labels=c("Comfort","Challenge","Control"))
RattanData <- data.frame(Feedback,Motivation)
```

### Analyses of the Different Groups

```{r}
estimateMeans(Motivation~Feedback)
```

```{r,Rattan-Means}
plotMeans(Motivation~Feedback,ylab="Motivation")
```

### Analysis of a Group Difference

```{r}
Comparison <- factor(Feedback,c("Comfort","Challenge"))
estimateDifference(Motivation~Comparison)
```

```{r,Rattan-Difference}
plotDifference(Motivation~Comparison,ylab="Motivation")
```

```{r}
standardizeDifference(Motivation~Comparison)
```

### Analysis of a Group Contrast

```{r}
ComfortvsOthers <- c(-1,.5,.5)
estimateContrast(Motivation~Feedback,contrast=ComfortvsOthers)
```

```{r,Rattan-Contrast}
plotContrast(Motivation~Feedback,contrast=ComfortvsOthers,labels=c("Comfort","Others"),ylab="Motivation")
```

```{r}
testContrast(Motivation~Feedback,contrast=ComfortvsOthers)
```

```{r}
standardizeContrast(Motivation~Feedback,contrast=ComfortvsOthers)
```
