---
title: "Estimation Approach to Statistical Inference"
author: "Craig A. Wendorf"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{OneWay (Between-Subjects) Example with Rattan Summary Statistics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,include=FALSE}
library(EASI)
```

## OneWay (Between-Subjects) Example with Rattan Summary Statistics

### Enter Summary Statistics

```{r}
Comfort <- c(N=18,M=3.333,SD=1.917)
Challenge <- c(N=17,M=5.265,SD=1.448)
Control <- c(N=19,M=4.447,SD=1.433)
RattanSummary <- rbind(Comfort,Challenge,Control)
class(RattanSummary) <- "bss"
```

### Analyses of the Different Groups

```{r}
estimateMeans(RattanSummary)
```

```{r,Rattan-Means}
plotMeans(RattanSummary,ylab="Motivation")
```

### Analysis of a Group Difference

```{r}
ComfortvsChallenge <- rbind(Comfort,Challenge)
class(ComfortvsChallenge) <- "bss"
estimateDifference(ComfortvsChallenge)
```

```{r,Rattan-Difference}
plotDifference(RattanSummary,contrast=ComfortvsChallenge,ylab="Motivation")
```

```{r}
standardizeDifference(ComfortvsChallenge)
```

### Analysis of a Group Contrast

```{r}
ComfortvsOthers <- c(-1,.5,.5)
estimateContrast(RattanSummary,contrast=ComfortvsOthers)
```

```{r,Rattan-Contrast}
plotContrast(RattanSummary,contrast=ComfortvsOthers,labels=c("Comfort","Others"),ylab="Motivation")
```

```{r}
testContrast(RattanSummary,contrast=ComfortvsOthers)
```

```{r}
standardizeContrast(RattanSummary,contrast=ComfortvsOthers)
```
