---
title: "Estimation Approach to Statistical Inference"
author: "Craig A. Wendorf"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{Analyze - Repeated Measures (Within-Subjects) Tutorial with Summary Statistics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,include=FALSE}
library(EASI)
```

## Analyze - Repeated Measures (Within-Subjects) Tutorial with Summary Statistics

### Enter Summary Statistics

```{r}
Outcome1 <- c(N=4,M=2.000,SD=2.449)
Outcome2 <- c(N=4,M=6.000,SD=2.449)
Outcome3 <- c(N=4,M=7.000,SD=2.449)
RepeatedSummary <- rbind(Outcome1,Outcome2,Outcome3)
class(RepeatedSummary) <- "wss"

RepeatedCorr <- declareCorrMatrix("Outcome1","Outcome2","Outcome3")
RepeatedCorr["Outcome1","Outcome2"] <- .500
RepeatedCorr["Outcome1","Outcome3"] <- .056
RepeatedCorr["Outcome2","Outcome3"] <- .389
RepeatedCorr <- fillCorrMatrix(RepeatedCorr)
```

### Analyses of Multiple Variables

```{r,AnalyzeRepeated-MeansA}
analyzeMeans(RepeatedSummary)
```

```{r,AnalyzeRepeated-MeansB}
analyzeMeans(RepeatedSummary,mu=5,conf.level=.99,rope=c(3,7))
```

### Analyses of a Variable Comparison

```{r}
CompSummary <- RepeatedSummary[c("Outcome1","Outcome2"),]
class(CompSummary) <- "wss"
```
```{r,AnalyzeRepeated-DifferenceA}
analyzeDifference(CompSummary,RepeatedCorr)
```

```{r,AnalyzeRepeated-DifferenceB}
analyzeDifference(CompSummary,RepeatedCorr,mu=-2,conf.level=.99,rope=c(-2,2))
```

### Analyses of a Variable Contrast

```{r}
O1vsOthers <- c(-1,.5,.5)
```
```{r,AnalyzeRepeated-ContrastA}
analyzeContrast(RepeatedSummary,RepeatedCorr,contrast=O1vsOthers)
```

```{r,AnalyzeRepeated-ContrastB}
analyzeContrast(RepeatedSummary,RepeatedCorr,contrast=O1vsOthers,mu=4,conf.level=.99,rope=c(-2,2))
```
