---
title: "Estimation Approach to Statistical Inference"
author: "Craig A. Wendorf"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{Analyze - OneWay (Between-Subjects) Tutorial with Summary Statistics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,include=FALSE}
library(EASI)
```

## Analyze - OneWay (Between-Subjects) Tutorial with Summary Statistics

### Enter Summary Statistics

```{r}
Level1 <- c(N=4,M=2.000,SD=2.449)
Level2 <- c(N=4,M=6.000,SD=2.449)
Level3 <- c(N=4,M=7.000,SD=2.449)
OneWaySummary <- rbind(Level1,Level2,Level3)
class(OneWaySummary) <- "bss"
```

### Analyses of Multiple Groups

```{r,AnalyzeOneWay-MeansA}
analyzeMeans(OneWaySummary)
```

```{r,AnalyzeOneWay-MeansB}
analyzeMeans(OneWaySummary,mu=5,conf.level=.99,rope=c(3,7))
```

### Analyses of a Group Comparison

```{r}
CompSummary <- OneWaySummary[c("Level1","Level2"),]
class(CompSummary) <- "bss"
```
```{r,AnalyzeOneWay-DifferenceA}
analyzeDifference(CompSummary)
```

```{r,AnalyzeOneWay-DifferenceB}
analyzeDifference(CompSummary,mu=-2,conf.level=.99,rope=c(-2,2))
```

### Analyses of a Group Contrast

```{r}
L1vsOthers <- c(-1,.5,.5)
```
```{r,AnalyzeOneWay-ContrastA}
analyzeContrast(OneWaySummary,contrast=L1vsOthers)
```

```{r,AnalyzeOneWay-ContrastB}
analyzeContrast(OneWaySummary,contrast=L1vsOthers,mu=4,conf.level=.99,rope=c(-2,2))
```
