---
title: "Estimation Approach to Statistical Inference"
author: "Craig A. Wendorf"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{Pairwise Comparisons - OneWay (Between-Subjects) Tutorial with Summary Statistics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,include=FALSE}
library(EASI)
```

## Pairwise Comparisons - OneWay (Between-Subjects) Tutorial with Summary Statistics

### Enter Summary Statistics

```{r}
Group1 <- c(N=4,M=2.000,SD=2.449)
Group2 <- c(N=4,M=6.000,SD=2.449)
Group3 <- c(N=4,M=7.000,SD=2.449)
OneWaySummary <- rbind(Group1,Group2,Group3)
class(OneWaySummary) <- "bss"
```

### Analyses of Pairwise Comparisons

#### Confidence Intervals for the Pairwise Comparisons

```{r}
estimatePairwise(OneWaySummary)
```

```{r}
estimatePairwise(OneWaySummary,conf.level=.99)
```

#### Plots of the Confidence Intervals for the Pairwise Comparisons

```{r,OneWay-PairwiseA}
plotPairwise(OneWaySummary)
```

```{r,OneWay-PairwiseB}
plotPairwise(OneWaySummary,mu=-2,conf.level=.99,rope=c(-4,0))
```

#### Significance Tests of the Pairwise Comparisons

```{r}
testPairwise(OneWaySummary)
```

```{r}
testPairwise(OneWaySummary,mu=-2)
```

#### Effect Sizes for the Pairwise Comparisons

```{r}
standardizePairwise(OneWaySummary)
```

```{r}
standardizePairwise(OneWaySummary,conf.level=.99)
```
