---
title: "Estimation Approach to Statistical Inference"
author: "Craig A. Wendorf"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    keep_md: TRUE
vignette: >
  %\VignetteIndexEntry{Relational Intervals - OneWay (Between-Subjects) Tutorial with Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=7, fig.height=5,fig.path='figures/',echo=TRUE,warning=FALSE,message=FALSE)
```

```{r,include=FALSE}
library(EASI)
```

## Relational Intervals - OneWay (Between-Subjects) Tutorial with Data

### Enter Data

```{r}
Factor <- c(rep(1,4),rep(2,4),rep(3,4))
Outcome <- c(0,0,3,5,4,7,4,9,9,6,4,9)
Factor <- factor(Factor,levels=c(1,2,3),labels=c("Group1","Group2","Group3"))
OneWayData <- data.frame(Factor,Outcome)
```

### Relational Intervals

```{r}
estimateRelational(Outcome~Factor)
```

```{r,OneWay-RelationalA}
plotMeans(Outcome~Factor)
addRelational(Outcome~Factor)
```

```{r,OneWay-RelationalB}
plotRelational(Outcome~Factor)
```

```{r,OneWay-RelationalC}
plotRelational(Outcome~Factor,conf.level=.99,mu=5)
```
